spring:
  application:
    name: api
  data:
    web:
      pageable:
        page-serialization-mode: via-dto
  config:
    import: optional:file:.env[.properties]      
  datasource:
    url: ${DB_POSTGRES_URL}
    username: ${DB_POSTGRES_USERNAME}
    password: ${DB_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
  cache:
    type: simple